### ISSUE TITLE
Migrating from pino 5 to pino 6 makes problems

### ISSUE THREAD

**Issue by Ognian** [pinojs/pino#1048]
With migrating from v.5 to v.6 you changed the way the logger works. #795 provides a code snipped that should restore the previous functionality BUT unfortunately it doesn't!

One reason is since it cares only about 2 arguments where previously there could have been more also.
Another reason is that it doesn't check if the first argument contains already %j or %s or ... placeholders.

Has someone a better implementation?

**Comment by jsumners** [comment]
This was covered in the release notes https://github.com/pinojs/pino/releases/tag/v6.0.0

**Comment by Ognian** [comment]
Unfortunately this is NOT the case!

**Comment by kibertoad** [comment]
@Ognian Could you please explain?

**Comment by Ognian** [comment]
I have a long growing code base. Somewhere in the beginning it was Bunyan then I migrated to pino. There are thousand of logging entries and the only way you can know if they really work is by trying each and every edge case of the app which is impossible. Now you removed the compatibility with Bunyan, since this is what the change is about. The workaround I found was:
```
 hooks: {
      // logMethod needed when migrating existing code base from pino 5 to pino 6
      logMethod(inputArgs, method) {
        if (inputArgs.length === 2 ) {
          // eslint-disable-next-line no-param-reassign
          inputArgs[0] = `${inputArgs[0]} %j`
        }
        return method.apply(this, inputArgs)
      }
    }
```
But what about if it is called with: `logger.info('hello', a, b)` then `b` is not displayed.
What about the call `logger.info('hello %j', a)`then the above workaround prints an `hello %j a`
etc...

I expect one job from a logger -> to log everything; and I lost the confidence that pino will do this right.

**Comment by kibertoad** [comment]
@Ognian Isn't this exactly what linked document states?
```
Previously, Pino emulated Bunyan's behavior when interpreting logs like:

    log.info('a message', { an: 'object'})
    log.info('a', 'silly', 'message')

The old behavior would result in 1 yielding "msg":"a message {\"an\":\"object\"}" and 2 yielding
"msg":"a silly message". As of this release, 1 will yield "msg":"a message" and 2 will yield "msg":"a".

To get the same results in Pino v6 as in previous releases actual format identifiers should be provided, e.g.:

    log.info('a message %j', { an: 'object' })
    log.info('a %s %s', 'silly', 'message')
```

**Comment by Ognian** [comment]
@kibertoad the full picture is:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1231174/124290317-93995480-db53-11eb-8608-c4045f50fd80.png">
and when reading the #795 merging request (the last blue link) you can read about the suggested workaround...

Anyway, this discussion is going in the wrong direction.
The actual question is if already someone has a **proven** solution.

**Comment by Ognian** [comment]
just to clarify: the suggested solution, to inspect and possibly rewrite EVERY log statement is practically not feasible!
The only feasible way is to restore the previous behavior...

**Comment by kibertoad** [comment]
@Ognian I'm sorry, but that sounds like a contradicting statement. The fact that you dislike the change in behaviour does not mean that it was not documented or communicated. It was a semver major change for a reason, and the way it behaves now is intentional. If you want logger to work differently - probably your best bet is to write your own wrapper that would be preprocessing passed parameters prior to feeding it to pino.
It is not feasible to expect original behaviour to be restored. If you need it back, you can revert back to pino 5.

**Comment by Ognian** [comment]
@kibertoad thanks for the clear answer.
I now understand that you don't care about providing continuity in this project.

**Comment by jsumners** [comment]
The release notes are very clear about the behavior change. The prior behavior was surprising behavior and came with arcane rules about what would happen depending on what parameters were passed in which position. Pino is established enough on its own by the time of the change that we no longer need to restrict ourselves to matching the API of a long outdated module. 

Your example log hook _does not match_ the documented compatibility hook (https://getpino.io/#/docs/api?id=logmethod). Please do not alter the example and then complain that it does not work. For reference, this is what the docs look like: 

![image](https://user-images.githubusercontent.com/321201/124297271-e6a9e200-db28-11eb-996c-360c64fcd7a0.png)

**Comment by davidmarkclements** [comment]
For anyone reading this, this is an example of how not to interact with an OSS project. 

@Ognian as per the semver standard (see semver.org) continuity is provided via patch and minor version updates. A major release, is by definition a breaking change. 

In order to avoid being a resource drain on projects that provide software that you use for free in future, I'd encourage you to alter the way you communicate with OSS projects and be sure to understand the Semver standard and how a given project operates before making ill-conceived statements about priorities.
