### ISSUE TITLE
V7 transports and Typescript

### ISSUE THREAD

**Issue by oddeirik** [pinojs/pino#1243]
I've tried creating a super-simple wrapper for using pino-seq with the new worker thread transports introduced in Pino v7, but it looks like this won't work right out of the box, at least not with the setup we're running.

Pino logger transport config:
`transport: { target: path.join(__dirname, 'pinoSeqStream.js') }`

And the transport itself:
```
// pinoSeqStream.ts
import { createStream, SeqConfig } from 'pino-seq';

export default (config: SeqConfig) => {
  return createStream(config);
};
```
This transpiles into the following:
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const pino_seq_1 = require("pino-seq");
exports.default = (config) => {
    return (0, pino_seq_1.createStream)(config);
};
//# sourceMappingURL=pinoSeqStream.js.map
```

When running the node application, I just get the following error:
```
[...]\node_modules\thread-stream\lib\worker.js:38
  destination = await fn(workerData.workerData)
                      ^
TypeError: fn is not a function
```

I'm guessing this is down to how tsc transpiles this to JS? Any pointers on how one can create these new transports with Typescript? Are there any specific requirements for tsc/tsconfig.json that needs to be set?

I briefly looked at Typescript 4.5 and its ES modules support, but that was scrapped by the TS team for now, and is only available as an experimental feature in typescript@next.

**Comment by oddeirik** [comment]
I just realized I can circumvent the whole file/module loading by using the destination argument directly in pino, but will that spawn a worker thread or will it just do in-process logging?

```
const destinationStream = !process.env.IS_PROD_ENV
  ? pino.transport({ target: 'pino-pretty' })
  : pinoSeqStream({
      serverUrl: 'some-server-url',
      apiKey: 'some-seq-api-key',
      logOtherAs: 'Information',
    });

const pinoLogger = pino({ level: process.env.LOG_LEVEL, /* and so on */ }, destinationStream);
```

I'm a little confused about the differences between transport and destination in pino, tbh 😅

**Comment by davidmarkclements** [comment]
A destination is *main thread*. We don't recommend applying log processing in the main thread, as this uses up valuable event-loop cycles that will affect your apps performance. 

A transport is a *worker thread* - logs are written to a shared array buffer, where they are picked up in the worker thread and then processed accordingly. This applies the least pressure to the main thread event loop, meaning you app performs better. Also, transports have better data reliability - even if you've got one tick left in the main thread (e.g. you're in a process.on('exit') handler), we pause the main thread (using [Atomics](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics])) and then do as much final asynchronous work as needed in the transport worker. 

The reason your code is indeed to do with the transpiling from. 

https://github.com/pinojs/thread-stream/blob/main/lib/worker.js#L21-L38

thread-stream tries to load your file, in two places. The first one is using a dynamic import, this to load a *native* esm file. Native esm has a `default export` syntax, when loaded with the dynamic `import` function this `default export` appears as the `default` property on the resolved module object. However since your actual code isn't ESM, it's transpiled TS this is converted to CJS syntax. Normally when you want to export a default function in CJS you do `module.exports = function () {}`. However, because TS supports *faux ESM* (syntactically alike, behaviourally different) it's creating a module with the shape `{ default: function () {} }`. So because it's CJS it's loaded on this line: https://github.com/pinojs/thread-stream/blob/main/lib/worker.js#L33. Which means when this line is reached, https://github.com/pinojs/thread-stream/blob/main/lib/worker.js#L38, `fn` is not a function, its an object with a `default` property, hence the error. 

@mcollina I don't know if we want to patch this so that it calls fn OR fn.default even in CJS cases? 

@oddeirik for a quick solution you could just not compile this specific file and not worry about the types, or you could change the typescript compiling options for this (if any apply, I'm no TS expert)

**Comment by oddeirik** [comment]
So I kind of got it working, although using the pino-seq package wrapped directly didn't work (no idea why, it just logged to stdout instead), so I ended up rewriting it as a separate function which returned a regular writable (pino-seq does a `class PinoSeqStream extends stream.Writable` instead):

```
const pinoSeqStream = (config: SeqStreamOptions) => {
	  [...]
	  // Functions to parse and log to seq
	  [...]
	  const stream = new Writable({
	        write(chunk, _encoding, callback) {
			  [...]
		  };
		  return stream;
	  });
};
// Export it like this
export = pinoSeqStream;
```
That last line is apparently the trick to tell tsc to do cjs style exports. Probably a 'duh' moment for those more familiar with tsc, but hey, I learned something. I think...

**Comment by dflor003** [comment]
I was just getting this error as well. 

Around line 21 in `thread-stream/lib/worker.js` it tries to find the default export like so:

```js
try {
    fn = (await realImport(workerData.filename)).default
  } catch (error) {
```

After some troubleshooting and adding log statements to the `thread-stream/lib/worker.js` file, what I noticed is that if you have your transport like the following:

```ts
export default async function myTransport() {
...
}
```

The object structure you get after `realImport` does its thing is something like:

```js
{
  __esModule:true,
  default: { default: <your function> }
}
```

Notice the doubly nested `default`. The only way I was able to work around this is by exporting it in every way possible:

```ts
export async function myTransport() {
...
}

module.exports = myTransport;
export default myTransport;
```

That got it working for me, but I'd be curious to see why this is even happening when compiled with tsc... Took me hours to figure it out. Any chance it could be these tsc compiler flags? If so, is there anything on the pino side that could change to accommodate this?

```json
{
  "allowSyntheticDefaultImports": true,
  "esModuleInterop": true
}
```

**Comment by mcollina** [comment]
Something you could do is to open a PR that can handle the "double nested default".

**Comment by EdisonHarada** [comment]
@oddeirik @dflor003 Did you guys by any chance managed to make it work locally?

With both options of adding `module.exports = myTransport` and `export =  myTransport` worked after I build it, but not locally.

**Comment by EdisonHarada** [comment]
@oddeirik Sorry when I said build it was related to compiling the typescript code to js.

So currently I'm using ts-node to run it locally, but for some reason even exporting in the way that you mentioned doesn't work, but after compiling it with `tsc` it works.

I was just wondering if you guys managed to make it run.

In my setup I have the `transport.ts` file
```
const myTransport = (opts = {}) => {
.....
}
export = myTransport
```

And the `logger.ts` that I instantiate it:
```
....
const logger = pino(options, pino.transport({
      target:
        './transport',
      options: {
          ...
      },
    }))
....
```

So it won't work unless I compile it, I just couldn't figure out why.

**Comment by oddeirik** [comment]
I don't know how ts-node works, but if it's just a "wrapper" that first runs tsc and then node, I guess it should work just like when doing it manually. Are you getting errors about the function/export itself or is it an issue loading the file itself? If it's the latter, it's probably a matter of paths and where the file actually resides when executing it via ts-node.

Maybe try using path.join and __dirname macro to resolve the transport file path? E.g `target: path.join(__dirname, 'transport.js'),`. Also, I think you need to to use the full filename, including the .js extension.

**Comment by mcollina** [comment]
@kibertoad maybe you can help here.

**Comment by kibertoad** [comment]
sure, I can take a look tomorrow

**Comment by EdisonHarada** [comment]
@oddeirik I checked here and without the extension and it works fine :) (when I use ts-node to run it actually try to find the file with .ts and in runtime it tries to find the .js file).

As I'm using some custom transports that will be shared between some internal projects I created a package with the transport, so it works fine locally with ts-node and also after compiling it as the package is already compiled into javascript.

The only thing required is as you guys mentioned before either the extra `module.exports = myTransport` or `export = myTransport`.

**Comment by hp8wvvvgnj6asjm7** [comment]
This is how I use worker_threads with various startup methods

```
        // @ts-ignore
        if(process[Symbol.for("ts-node.register.instance")]){
            this._thread = new Worker(`require('ts-node/register');require(require('worker_threads').workerData.path);`, { eval: true, workerData: { path: path.join(__dirname, 'PlotServiceWorker.ts'), port}})
        }else if(process.env.TS_NODE_DEV){
            this._thread = new Worker(`require('ts-node-dev');require(require('worker_threads').workerData.path);`, { eval: true, workerData: { path: path.join(__dirname, 'PlotServiceWorker.ts'), port}})
        }else{
            this._thread = new Worker(`require(require('worker_threads').workerData.path);`, { eval: true, workerData: { path: path.join(__dirname, 'PlotServiceWorker.js'), port}})
        }

```

**Comment by mcollina** [comment]
Would you like to send a PR to add support for the above to https://github.com/pinojs/thread-stream/blob/2dd56b633d32a2cd8f2096f46b97cbed9e537662/index.js#L50?

**Comment by Lil-Strudel** [comment]
Any update on this issue?

**Comment by mcollina** [comment]
@kibertoad is this something you can look into?

**Comment by Niceplace** [comment]
@EdisonHarada Can you share how you managed to make it work with `ts-node`? I'm trying some basic examples to get familiar with transports because I have to write a custom one. At this point have tried every possible thing that I can think of I cannot get it to work. The same code in Javascript executes beautifully tho! 😅 

Using ts-node with NodeJS 16.14 on MacOS, I always get this:

```
/Users/sbeaulieu/workspace/test-datadog-pino/app/node_modules/thread-stream/index.js:281
      throw new Error('the worker has exited')
```

To run the app I tried `ts-node main.ts`, `node --register ts-node/register main.ts`, I even tried using the `worker.execArgv` option when defining the transport because I suspected that the worker thread had trouble with Typescript but it doesn't seem to change anything


My code: 

`main.ts`

```
import { pino } from 'pino';

const transport = pino.transport({
  target: './customTransport',
});

const main = () => {
  pino(transport).info(
    { metadata1: 'hello', metadata2: 'hi' },
    'Hello some log entry ',
  );
};

main();
```

`customTransport.ts`

```
import build from 'pino-abstract-transport';

const defaultParseLine = (line: any) => {
  const obj = JSON.parse(line);
  // property foo will be added on each line
  obj.foo = 'bar';
  return obj;
};

const transport = (opts: any) => {
  const parseLine =
    typeof opts.parseLine === 'function' ? opts.parseLine : defaultParseLine;
  return build(
    (source) => {
      source.on('data', (obj) => console.log(obj));
    },
    {
      parseLine: parseLine,
    },
  );
};

// I also tried export default, export =
module.exports = transport;
```

`tsconfig.json`

```
{
    "compileOnSave": true,
    "compilerOptions": {
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
      "module": "CommonJS",
      "moduleResolution": "node",
      "noEmit": true,
      "noImplicitAny": true,
      "noUnusedLocals": true,
      "outDir": "dist/",
      "skipLibCheck": true,
      "sourceMap": true,
      "strictNullChecks": true,
      "strict": true,
      "lib": ["ESNext"],
      "target": "ES5",
      "typeRoots": ["./node_modules/@types"]
    },
    "include": ["app/ts"],
    "exclude": ["node_modules", "dist"]
  }
```

`package.json`

```
{
  "name": "test-datadog-pino",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "dev": "ts-node ./ts/main.ts",
  },
  "dependencies": {
    "pino": "^7.6.5",
    "pino-abstract-transport": "^0.5.0",
    "ts-node": "^10.5.0",
    "typescript": "^4.5.5"
  }
}
```


I appreciate _any_ pointers. Cheers ! :D

**Comment by Niceplace** [comment]
This seemed promising since it seems that we can pass options to the worker when calling `pino.transport` : https://github.com/TypeStrong/ts-node/issues/711#issuecomment-679621830

Unfortunately, I don't think that the current implementation of transports allows passing code directly to the worker so it can be created with `eval: true` 

Now I'm really out of ideas 😅

**Comment by castarco** [comment]
If nobody is currently working on this issue, I'd like to pick it 🙂 . I'll start working on it tomorrow morning. Some good ideas have already been presented in this thread, I believe I can apply some of them plus a bit of extra polishing to improve the compatibility with TS & CJS modules.

**Comment by mcollina** [comment]
Go for it!

**Comment by mcollina** [comment]
@castarco could you send a PR to pino as well that tests this feature here too?

**Comment by castarco** [comment]
> @castarco could you send a PR to pino as well that tests this feature here too?

on it
