### ISSUE TITLE
Release Frequency

### ISSUE THREAD

**Issue by craigmcc** [pinojs/pino#1250]
I totally appreciate all the effort that you folks spend on adding things, fixing things, and making Pino better.

I totally do NOT appreciate the number of different releases from Pino in the last few weeks.  Anyone who has Dependabot alerts on their GitHub projects (like I do), for example, is getting totally inundated with notifications and pull requests.  Any of them that might actually be applicable require testing before acceptance -- and it does not please me to have to do that five times on each project if I want to stay up to date.

**Comment by jsumners** [comment]
Thank you for the input. You are welcome to track releases at your own cadence by tweaking the tools you use.

**Comment by kibertoad** [comment]
@craigmcc I feel your pain. As @jsumners has put it, if you find notifications excessive, you can configure Dependabot to check for updates on a less regular basis, e. g. weekly. Unfortunately, we cannot reduce the cadence of releases, because that would mean that some of our users, who might be dependent on certain upcoming features or fixes, might get blocked. When weighed against (mild and solvable) inconvenience for other users, we generally choose to err on the side of more frequent releases.

**Comment by craigmcc** [comment]
As you undoubtedly know, lowering the Dependabot check frequency does so
for *all* checks, not just this one.  That's not acceptable to me.

I will just train myself to ignore things from Pino.  Especially for a
dot-dot release for a documentation change.

**Comment by kibertoad** [comment]
@craigmcc Check this Dependabot option: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#ignore

**Comment by mojavelinux** [comment]
As a user of pino myself, I do not agree with this compliant. I think frequent releases are good as it keeps the project healthy. That fact that the concern relates to the behavior of separate software makes it even more off base for me. I've long held that dependabot has very poor defaults and the problem is really with dependabot. I support the decision of the pino developers to make regular releases and I think it shows just how strong the health of this project is.
