### ISSUE TITLE
pino-debug

### ISSUE THREAD

**Issue by davidmarkclements** [pinojs/pino#128]
I'd like to recreate the `debug` value proposition in a pino compatible way

debug is a different use case (dev more than prod) - but I've also seen teams using debug for prod logging - I'm thinking,  let's create a module that namespaces debug logs as per the `debug` module, and applies filtering to `pino.debug` logs

```js
var logger = require('pino')()
var debug = require('pino-debug')
debug('myApp', logger)

pino.debug('ok')
```

```sh
$ DEBUG=myApp node my-app.js # pretty prints ok, same output as debug module
```

this could be as simple as overriding `pino.debug` with the debug module, whenever the DEBUG var is set

@mcollina @jsumners thoughts?

**Comment by jsumners** [comment]
I have used `debug` once or twice because it seemed to be "the way things are done." But I'm not really a fan. In my opinion the reasoning behind `debug` is that the library using it shouldn't have its own logger because it is meant to be included in a larger application (which would have its own logger). I think in such cases that if logging is to be done then it should:

1. require `abstract-logging`
2. log all development, aka `debug`, logs to `.trace()`
3. log error messages to `.error()`
4. log error stack traces to `.debug()`
5. tell the user of the library that they can supply an `abstract-logging` compatible logger to get messages, e.g. `pino`

Items 3 and 4 are optional; I just like to do it that way.

That being said, I'm not opposed to `pino-debug` existing.

**Comment by mcollina** [comment]
I'm not fond of the idea of `pino-debug`. We should probably do something new for development. Recently I'm doing `tap test.js | pino` to get some good looking output.

We can easily draw some parallelism between debug ENV filters and pino child loggers. We _might_ just need a way to control those using ENV.

**Comment by marwanhilmi** [comment]
Perhaps another interesting idea is to at least capture `debug` logs. Many libraries are using `debug` internally, so it would be great if we could setup Pino to capture those logs and route to a single location.

**Comment by davidmarkclements** [comment]
@marwanhilmi you've just opened up a whole new way to think about this

require pino-debug in your entry point, if NODE_ENV is production, all debug logs are enabled but go through pino (also, we could allow a mapper, so each name space could be mapped to a log (info, error, debug etc) type if desired.

This would really create a logging firehose on, because all you deps logs (and core too if we want) would be turned on

**Comment by mcollina** [comment]
Let me want to address two problems:

a. intercept the debug content of dependencies we have no control with
b. easy migration from debug of apps from debug to pino

IMHO, we should do the first.
If `NODE_ENV=production` and if `NODE_DEBUG=express:*`, all express related content ends up in the debug (or trace?) debug layer. Enabling everything is a little bit scary, because we might loose some flexibility that debug gives us.

**Comment by davidmarkclements** [comment]
i think 1 too - what if we actually do 

```
$ PINO_TRACE=fs,net,http PINO_DEBUG=express:* PINO_INFO=myApp:* node app.js
```

**Comment by jsumners** [comment]
I really don't like relying on environment variables. They are an external state that make it difficult to figure out what is wrong when their presence is missing or the are set incorrectly.

**Comment by mcollina** [comment]
I absolutely agree with you @jsumners. This is a way to get some data out from `debug`. I'm not even sure it's a good idea.

**Comment by davidmarkclements** [comment]
the value here for a production set up is fine grain control over debug output that's in the same logging format, with minimum overhead.

The other way is an options object

```js
require('pino-debug')({
  trace: 'fs, http, net',
  debug: 'express:*',
  info: 'myApp:*'
})
```

**Comment by jsumners** [comment]
I like the options object route. But I do understand the desire to replicate as much as possible the `debug` methodology. I would be happy if the options object accepted a `useEnv: true` property so that it is clear to the reader where to look for the rest of the configuration. And any other properties supplied, `trace`, `info`, etc. could override the settings in the environment.

**Comment by davidmarkclements** [comment]
PoC - https://github.com/pinojs/pino-debug
Note the benchmarks: https://github.com/pinojs/pino-debug#benchmarks

Only thing left is to get feedback and write unit tests /cc @jsumners @mcollina

**Comment by davidmarkclements** [comment]
also try out the example folder  (express app with `pino-debug`)

**Comment by mcollina** [comment]
Preloaders are awesome. Go ahead and release that, add something to the README over here as well. Good job Dave!

**Comment by jsumners** [comment]
Very crafty. I'm quite impressed. 

Seeing how you're applying runbench to more things, I suppose it really should be made into its own module. Let's discuss it and figure out what it would really need to be complete.
