### ISSUE TITLE
Possible RCE?

### ISSUE THREAD

**Issue by tinawng** [pinojs/pino#1317]
I use Pino to log incoming http request like so:
```javascript
const http2 = require('http2');
const pino = require('pino'), logger = pino(pino.destination({ dest: process.env.LOG_PATH + 'logs', minLength: 4096, sync: false }))
logger.level = 'trace';
setInterval(() => { logger.flush() }, 3000).unref();

http2.createSecureServer({
    key: ... ,
    cert: ... ,
    allowHTTP1: true
}, function (request, response) {
    // 🔊 Log request
    logger.trace(request);
   ...
```
when checking my logs I saw this: https://pastebin.com/1YmkcNtV
(sry for the pastebin but it's quite a big chunk)

I know I have to be responsible somewhere but I was wondering if it was not also a vulnerability inside Pino.

**Comment by mcollina** [comment]
Please follow https://github.com/pinojs/pino/blob/master/SECURITY.md and share a script to reproduce.

Due to the output you have shared, there is quite a lot happening. You are likely dumping some internal memory that should not be there.

Part of the problem is that you are logging the request object without a serializer:

```js
logger.trace({ req })
```

Would do the trick.

**Comment by tinawng** [comment]
Thank you for your answer!
sorry for the double post btw, github is acting weirdly right now..
