### ISSUE TITLE
Pino Transport log level is ignored

### ISSUE THREAD

**Issue by proviral** [pinojs/pino#1363]
Hey, 

I believe I may have found an issue in Pino.Transport with regards to the log level: 

Code:
```
const transport = pino.transport({
  target: 'pino/file',
  level: logOptions?.level || 'info',  // logOptions.level = "debug"
  options: {
    destination: path.join(filepath, filename),
    mkdir: true
  }
});

console.log(`Initializing File Logger @ Destination: ${path.join(filepath, filename)}`);
const logger = pino(transport);
```

Observation: 
> logger.level is set to 'info'

**Comment by mcollina** [comment]
A transport does not have a log level, you need to set the log level into pino itself.

**Comment by proviral** [comment]
@mcollina Your transport logs make reference to it.
![image](https://user-images.githubusercontent.com/10924735/158261331-008ae72f-f41f-4811-8dac-1d819f4197e1.png)

**Comment by mcollina** [comment]
that's within the `targets` option

**Comment by proviral** [comment]
So there is a difference between a base target and a list of targets?

**Comment by krouw** [comment]
Testing on the [transport example](https://github.com/pinojs/pino/blob/master/examples/transport.js), when configuring a list of targets, they only work with the configured level and omit the root level. I don't know if it is the expected behavior, however, it would be interesting to be able to change the root level and also change the level of the targets or configure a root target apart from the list of targets, since if for some reason you need to change the level at runtime , you can only do it by setting a target as root as shown in [basic example](https://github.com/pinojs/pino/blob/master/examples/basic.js)
