### ISSUE TITLE
Multistream dedupe example in documentation does not work

### ISSUE THREAD

**Issue by celebro** [pinojs/pino#1506]
The following example from documentation about `dedupe` flag in `multistream` (https://github.com/pinojs/pino/blob/master/docs/api.md#pino-multistream) does not work as intended, it only logs `info` and `error`, while `debug` and `fatal` are ignored.

```javascript
var pino = require('pino')
var multistream = pino.multistream
var streams = [
  {stream: process.stdout},
  {level: 'error', stream: process.stderr},
]

var opts = {
    levels: {
        silent: Infinity,
        fatal: 60,
        error: 50,
        warn: 50,
        info: 30,
        debug: 20,
        trace: 10
    },
    dedupe: true,
}

var log = pino({
  level: 'debug' // this MUST be set at the lowest level of the
                // destinations
}, multistream(streams, opts))

log.debug('this will be written ONLY to process.stdout')
log.info('this will be written ONLY to process.stdout')
log.error('this will be written ONLY to process.stderr')
log.fatal('this will be written ONLY to process.stderr')
```

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by celebro** [comment]
I'm afraid I can't dedicate the time for implementing a fix, I can only add what I'm currently using instead is specifying a stream for every log level:

```javascript
var streams = [
    { level: 'debug', stream: process.stdout },
    { level: 'info', stream: process.stdout },
    { level: 'warn', stream: process.stdout },
    { level: 'error', stream: process.stderr },
    { level: 'fatal', stream: process.stderr }
];
```

**Comment by bl00dhound** [comment]
Hi, there!
There are two parts of problem:
* if`dedup` is set to`true` log is sent to the stream with[ the same level only](https://github.com/pinojs/pino/blob/master/lib/multistream.js#L63). That's the reason why we can't find log with `fatal` level in `process.stderr` stream. I've fixed it in [my PR](https://github.com/bl00dhound/pino/commit/f631737f821cd36b00919b7c17c47a4fcd14cf40). 
* if level of stream isn't set initially, `info` level [will be set](https://github.com/pinojs/pino/blob/master/lib/multistream.js#L103) by default. So, `debug` logs can't put to the stream with `info` level. That's more complicated problem than the previous one because we need to synchronize two entities (pino-logger and multistream). pino-logger has access to streams array but multistream entity knows nothing about default level in pino-logger. Probably, as a solution, I could add a couple of lines in the documentation about independent default log level in streams. Does it make sense?

**Comment by mcollina** [comment]
should be fixed in latest master
