### ISSUE TITLE
Caveats link in README points to nowhere

### ISSUE THREAD

**Issue by gamtiq** [pinojs/pino#152]
`Caveats` link in TOC inside `README.md` is not functioning.

**Comment by jsumners** [comment]
I think the "caveats" link is supposed to go to `#user-content-caveats`. However, simply fixing the reference in the TOC will not fix the problem. If you attempt to use the "Pino in the Browser" it will not work. This is because the content is hidden behind the disclosure triangle. Once the content is expanded, then the link will work.

I think the only solution to this is to clean up our documentation. I'll have another go at that.

**Comment by mcollina** [comment]
@jsumners go ahead! I think we have all the relevant information. We might consider splitting it up into multiple files and linking.

**Comment by jsumners** [comment]
Fixed in #153
