### ISSUE TITLE
[Question] Missing log entries in GCP?

### ISSUE THREAD

**Issue by ErlendFax** [pinojs/pino#1573]
Some of our log entries go missing somewhere between our GKE cluster and Google Logs Explorer. This is most likely not a Pino-problem, but curious if anyone else has seen this.

When running `k logs myPod`, I see all entries, but not all of them are found in Logs Explorer. The strangest part is that when one log entry is missing, always is the following few log entries also missing. 

**Has anyone seen this behavior before?**

I have tried to find a common denominator causing this, but I'm struggling. A theory is that when the input object is in the "wrong" form it never shows up in Logs Explorer.

We are using a small wrapper around pino, but this is basically how its used:
```typescript
this.pinoLogger = createLogger({ level: sanitizeLogLevel(level), name });
...
this.pinoLogger.info(optionalArguments, err); // optionalArguments?: Record<string, any>
```

Check out
<details closed>
<summary>Loggings that work</summary>
<br>

```typescript

export interface Message {
  percentage: number;
  deviceId: string;
  timestamp: DateTime;
}

this.pinoLogger.info({
            deviceId: message.deviceId, // string
          });

this.pinoLogger.info({
            percentage: message.percentage, // number
          });

this.pinoLogger.info({
          ...message,
          });

this.pinoLogger.info({
          ...message,
 timestamp: message.timestamp.toString(),
          });

```
</details>

<details closed>
<summary>Loggings that do NOT work</summary>
<br>

```typescript

export interface Message {
  percentage: number;
  deviceId: string;
  timestamp: DateTime;
}

this.pinoLogger.info({
            message: message
          });

this.pinoLogger.info({
            message
          });
```
</details>

This is probably not a Pino-specific problem, but didn't really know where to ask.

**Comment by metcoder95** [comment]
Hey! Not belong to Pino's team but can bring some clarity over this. The `message` attribute is a reserved word on Cloud Logging to be used as the main `message` property when parsing the logs in a way of `jsonPayload`.

That translates into the scenario where a JSON object is being streamed to Cloud Logging (either remotely or printed to `stdout` using any self-managed service from GCP) and the `message` property of the log is there but is not a `string` it will be automatically ignored. If `string`, it will be respected and will be the headline of your log when querying them on Logs Explorer.

That's why when printing the properties individually, it works, but when trying to print everything under `message` it doesn't 🙂

**Comment by ErlendFax** [comment]
Ah! Of course! Thank you!
