### ISSUE TITLE
addLevel is not working

### ISSUE THREAD

**Issue by HCanber** [pinojs/pino#167]
__pino 3.1.1__

This fails with: _TypeError: log.foo is not a function_

``` js
const pino = require('pino')
const log = pino()
log.addLevel('foo', 35)
log.foo('bar')
```

The tests does not show this because:
1. Levels added to one instance via the constructor will be added to new instances
2. Adding a level on the constructor works and there exists a test that verifies this. The test creates a new level with the options: `{level:'foo', levelVal: 35}`
3. The test that verifies `addLevel('foo', 35)` is working because it's executed __after__ the test in _(2)_, and because of _(1)_ it uses that function.

If the test in _(3)_ is modified to `addLevel('foo2', 35)`,  the test fails.

Here is some code to show the problem:

``` js
const log = pino({level:'foo', levelVal:35})
const log2 = pino()
log2.foo('should fail, but will work')
```

Three problems exists in the current solution
- `levels` object is shared
- `lscache` object is shared
- `addLevel` does not add a new property

I have a fix for this, which copies `levels` and `lscache` to the instances when new custom levels are added to them. If no custom levels are added the standard values on `Pino.prototype` is used.

Let me know if you want me to submit a PR.

**Comment by davidmarkclements** [comment]
Hi @HCanber thanks for catching this, we may need to tweak depending on how it affects benchmarks but a PR would be much appreciated!

**Comment by itavy** [comment]
Hi,

i have found a few issues which are related to this one:
1. silent level is not documented at all in docs (it has level 100) and if i try to a loglevel with that value if fails with "unknown log level" 
2. if i add a level via constructor it set logLevel it's value: 
  i think the lovLevel(s) added at construct time should not influence the behavior of the logger;
  
3. if i am using a custom logLevel for debugging purpose pretty.js will fail because it doesn't know corespondent color for that level;
  this can be fixed easy with a default color for unknown logLevels.

i think in the evening i will be able to look into this and submit a PR if it is ok.

**Comment by mcollina** [comment]
> silent level is not documented at all in docs (it has level 100) and if i try to a loglevel with that value if fails with "unknown log level" 

It's hidden because it's a maximum, you can't log at that level.

> if i add a level via constructor it set logLevel it's value: 
i think the lovLevel(s) added at construct time should not influence the behavior of the logger;

#168 and #169 should address this?

> if i am using a custom logLevel for debugging purpose pretty.js will fail because it doesn't know corespondent color for that level; this can be fixed easy with a default color for unknown logLevels.

Would you mind sending a PR for this?

**Comment by mcollina** [comment]
Also https://github.com/pinojs/pino/blob/master/pino.js#L103.

**Comment by jsumners** [comment]
@itavy setting the log level to the custom level at construction is by design. The theory is that if you are adding it at construction time, then you must want to log at that level. This is the only use case I have seen in the wild.

**Comment by itavy** [comment]
hi,

@jsumners i am thinking that specific loglevel to debug a specific problem without altering all the other logs. i have setup pino to log in elasticsearch and i am filtering all the requests for that level only; it helps a lot to be able to filter for debugging only your specific problem without having to scroll through all other;
and as i stated above i don't want to alter current log level since the custom loglevel is for something temporary to debug;

@mcollina i understand that it is maximum logLevel but this is not specified in docs; the problem was that the error message is missleading: it should say that that value cannot be overridden;
and if it is maximum it is not enforced; i can set a logLevel in constructor wit level 200 and it will logit
if it is ok with this approach i can create a PR with silent set on Number.POSITIVE_INFINITY and so it will solve the error problem and when you will set on silent it will be silent;

as for #168 and #169 i will look and test this evening

**Comment by mcollina** [comment]
> @mcollina i understand that it is maximum logLevel but this is not specified in docs; the problem was that the error message is missleading: it should say that that value cannot be overridden;
and if it is maximum it is not enforced; i can set a logLevel in constructor wit level 200 and it will logit
if it is ok with this approach i can create a PR with silent set on Number.POSITIVE_INFINITY and so it will solve the error problem and when you will set on silent it will be silent;

Go ahead, we will review it there!
