### ISSUE TITLE
Problem with IE10 and 'quick-format-unescaped'

### ISSUE THREAD

**Issue by RanzQ** [pinojs/pino#228]
Not sure how browserify handles this but I'm using webpack 2 and had to add this rule to transpile the dependency `quick-format-unescaped`:

```
  module: {
    rules: [{
      test: /\.js$/,
      include: path.join(__dirname, 'node_modules', 'quick-format-unescaped'), // This package doesn't support browser
      use: [{
        loader: 'babel-loader'
      }]
    }]
  }
```

IE10 didn't like `const` so this solves the problem.

**Comment by mcollina** [comment]
@davidmarkclements this is on you. It seems quick-format-unescaped points even to the wrong repository on github. Can you please fix the metadata? I'm happy to do a PR and a release, but **where**?

**Comment by davidmarkclements** [comment]
quick-format-unescaped does point to the right repo - (the quick-format) repo - it's just that its on the quick-format-unescaped branch. This made sense at the time because we wen't with -unescaped to solve integration issues with pino but any maintenance on quick-format-unescaped almost always applies to quick-format as well 

@RanzQ are we saying that when built with webpack... code fails in IE10 because of use of `const` in `quick-format-unescaped` ?

**Comment by RanzQ** [comment]
@davidmarkclements yes exactly. And what I've learned from webpack tutorials, node_modules should be excluded from the transpile process and if a package is meant to be used in browser, it should provide a transpiled version.

So my solution is a workaround which forces the transpile on that package.

**Comment by mcollina** [comment]
Here it is: https://github.com/davidmarkclements/quick-format/pull/9

**Comment by davidmarkclements** [comment]
merged - released v1.1.1 - updated pino package.json in pr #229

**Comment by davidmarkclements** [comment]
pino v4.2.4 released - thanks @RanzQ!

**Comment by RanzQ** [comment]
@davidmarkclements nice, works now. :)
