### ISSUE TITLE
why do NOT in-process transport?

### ISSUE THREAD

**Issue by medns** [pinojs/pino#262]
Custom logger is the most common requirement, use stdout ===> stdin is not the fastest way to write log.

**Comment by mcollina** [comment]
@medns because Node.js is single threaded, and thanks to the way we generate the JSON log lines we can have our blazing performance. If we pass around objects, we would not be able to have the same throughput on the Node.js application.

In our tests, this usually enables the application to generate more throughput than any other logger for Node.js.

In a lot of system you can have multiple containers just logging to stdout, and leaving to your orchestrator to centralize log lines.

However, this is absolutely feasible. As an example of in-process transport, check out https://github.com/pinojs/pino-multi-stream/blob/master/multistream.js and https://github.com/pinojs/pino/blob/master/docs/API.md#metadata.
