### ISSUE TITLE
supporting legacy IE strategy

### ISSUE THREAD

**Issue by sara-gudeman** [pinojs/pino#311]
IE10 throws an error in the console `Invalid calling object`. From the error message, it looks like whatever is calling the logger methods is bound incorrectly.

The solution I've found involves binding `logger[level]` to `_console` in the `set` and `asObject` functions in browser.js. Is this something worth incorporating into the main repo? Will there be unintended side effects? From looking through the code, I couldn't see any.

**Comment by mcollina** [comment]
did the latest release impact you?

cc @davidmarkclements

**Comment by sara-gudeman** [comment]
Thanks for the quick reply! I've only been working with the most recent release, so I'm not sure about previous ones.

**Comment by davidmarkclements** [comment]
the last change in #309 would have no effect on this, I imagine this has always been an issue

IE10's console object must behave in a way were the method throws if it's not specifically on the `console` object (chrome *used* to do this as well)

@sara-gudeman I think you're right, we need to bind (or at least `.call(console)`) - would you be interested in making a PR?

**Comment by jsumners** [comment]
I do recall having to have the tools open for the console object to exist in IE.

**Comment by sara-gudeman** [comment]
@davidmarkclements Definitely! I'll get that in.

**Comment by davidmarkclements** [comment]
just while I remember, it might instead work if we set the `console` object as the prototype of the `logger` object - this would be ultimately cleaner (but we could only set it if the console object is available (again in IE if the console isn't available then then all methods are noops)

**Comment by sara-gudeman** [comment]
Apologies, I've had a busy week and haven't been able to get to this. I'll have it by EOW. I think I'm misunderstanding, because isn't that taken care of by this line? `var logger = Object.create(proto)`

**Comment by davidmarkclements** [comment]
yes! you're absolutely right, I wrote the original code, I looked at it twice before I wrote the above and still missed it 😆 

ok so - yah that mustn't work then

ok... 

I've refactored a bit, so this might look slightly different, good news is this that `write.apply` and `write.call` only happens here now instead of all over .. 
but in these two lines https://github.com/pinojs/pino/blob/master/browser.js#L154-L155

I wonder if you change `this` to `console` in those lines will it work in IE10 (and IE11.. and IE9)

If so we could do

1. check if IE
2. use getPrototypeOf (supported since IE9) to find out if console is in the proto chain (e.g. `Object.getPrototypeOf(this) === _console ? _console : this`

* Might need to special case if `_console` is `undefined` (or `null`?) if IE clears the `console` object when the IE devtools isn't opened
* Might also need to check for `getPrototypeOf` method just in case a pre-ES5 browser is being used (e.g. IE8 and down - IE8 still has some (tiny) market share)

Also – being cognizant that you we're gearing up to PR I got the browser testing suite up to scratch (https://github.com/pinojs/pino/pull/314)

You can do `npm run browser-test`  to run browser tests in a browser environment (they also run in node which is handy for CI integration), and then open the provided URL in IE

(on a side note another task we need to look into is setting up [`zuul`](http://npm.im/zuul) for to run in a cloud test suite like saucelabs

**Comment by jsumners** [comment]
Let's read https://stackoverflow.com/questions/5472938/does-ie9-support-console-log-and-is-it-a-real-function

Which leads to:

```js
if (!window.console) window.console = {log: function () {}}
```

**Comment by sara-gudeman** [comment]
A few things to follow up on:
* The code snippet in point 2 works like a charm. My question is, why check if it's IE? `Object.getPrototypeOf` looks like it has cross-browser support above IE9.

* I've seen the line @jsumners mentioned as a way to handle the issue of IE 8 and below having console undefined. Is that how we want to handle IE8 issues?

* I ran the tests in IE10, and there are larger issues. It doesn't support Object.assign. I'll open up a PR for the changes to fix the binding (which takes care of typical use cases), but for generalized IE compatibility, I think polyfills might be necessary.

**Comment by davidmarkclements** [comment]
* we don't have a minimum specified IE version (I don't think)
* re console undefined check - @mcollina @jsumners we need to decide whether to support IE8 - it has greater market share than other IE legacy because of people still using WinXP (corporate, government, and fairly common in Asia too I think)
* I don't think we should include polyfills since we'll be punishing newer browsers on behalf of older browsers - I think there's enough distance now to instead document support, and advise on supporting legacy support - .e.g "To use Pino with IE10 you will need the [Object.assign polyfill](https://www.npmjs.com/package/object.assign)" and so on for all legacy browser.

**Comment by jsumners** [comment]
I cannot be convinced to support IE8. IE9 would even be a stretch.

**Comment by mcollina** [comment]
IMHO IE10 is a stretch. We should definitely not go down to IE8.
However in order to support these browsers we need to have some testing capability in place. How about we add SauceLabs?

**Comment by davidmarkclements** [comment]
@jsumners - I'm inclined to agree, on that. IE10 will do for now, 

if we agree there's a need for documentation on legacy support and required polyfills, @sara-gudeman would you be interested in writing that doc? If so I think we should look at making @sara-gudeman a collaborator for legacy browsers (in the same way that @watson is collaborator for legacy node) – that is, of course, if you're at all interested in that @sara-gudeman

**Comment by sara-gudeman** [comment]
@davidmarkclements For sure. I'm thinking the docs should be pretty straightforward. Just the minimum supported IE version, then steps to take if you want to use it for lower versions?

**Comment by jsumners** [comment]
That's sensible.

**Comment by davidmarkclements** [comment]
just catching up with this - @sara-gudeman are you still interested in being a collaborator for pino browser legacy? If so I think a good way forward is to create two PR's

1. one for docs
2. adding yourself to The Team section in readme (https://github.com/pinojs/pino#the-team)

**Comment by jsumners** [comment]
ping @sara-gudeman

**Comment by jsumners** [comment]
I'm going to close this due to inactivity. Please re-open if anything should change.

**Comment by vanyadymousky** [comment]
Good day/night/whatever, may I rise this up and ask for updates? Facing same issue in isomorphic parts of my application, going to fork and track this issue.

**Comment by mcollina** [comment]
@vanyadymousky I would recommend opening a new issue, and maybe send a PR about IE11.
