### ISSUE TITLE
Metadata API documentation

### ISSUE THREAD

**Issue by unjello** [pinojs/pino#388]
With the new API introduced by #386, I tried to update my prettifier to fit in (https://github.com/unjello/pino-pretty-min/pull/2). Most of it was quite straightforward, especially looking at *reference* prettifier by @jsumners (https://github.com/pinojs/pino-pretty), and *bin* version with the new factory and string/object handlers works fine. One thing I do not get tho, is how `asMetaWrapper` works. What is the meaning of the method itself, and all the parameters inside like `lastLevel`, `lastObj` or `chindings`. Not sure how to set them. Is it some boilerplate that will be more or less the same from one prettifier to another, or should (how?) each prettifier customize it?

**Comment by jsumners** [comment]
I think everyone understands why it's there. What could be clearer is the documentation for the underlying metadata API. Why do the `last` properties need to be set? What is meant by "last"? For `lastLevel` is it the level of the incoming log object? Or should the person using the API keep track of the previous log object so that they can specify that value?

I have updated the title of this issue to correctly reflect what is under discussion.

I will get the `asMetaWrapper` method migrated into the `cli-revamp` branch soon.

**Comment by mcollina** [comment]
@jsumners yes, `last` mean the incoming log object.

**Comment by jsumners** [comment]
Some documentation to that effect, and why Pino needs it would be great.

**Comment by davidmarkclements** [comment]
closing, the docs cover this now https://getpino.io/#/docs/api?id=destinationsymbolfor39pinometadata39
