### ISSUE TITLE
How do you preserve color output from other commands?

### ISSUE THREAD

**Issue by pajtai** [pinojs/pino#408]
Greater logger! I have a question:

I'm piping to the pino cli to parse and colorize Pino logs, but I sometimes have other output that comes with colors, and the pino cli removes these colors.

For example, I use eslint - which has colored output - how can I preserve that?

Example command `nodemon index.js --exec 'npm run lint && node' | pino`

**Comment by davidmarkclements** [comment]
By the time it reaches the prettifier (`pino`) there is no color.

Try the following:  `nodemon index.js --exec 'npm run lint && node' | cat`

You should see that there's no color, because in generally CLI tools that output 
color will check `process.stdout.isTTY` (or `require('tty').isatty()`) and then 
output the additional terminal codes (or not).

`node -p process.stdout.isTTY` -> true
`node -p process.stdout.isTTY | cat ` -> undefined

**Comment by davidmarkclements** [comment]
Closing for now, but if you want to keep colour through a pipe that's down to configuring which ever libs are outputting colour (if they have that option)

**Comment by pajtai** [comment]
@davidmarkclements Thanks for that info.
