### ISSUE TITLE
Bug: level prop in browser doesn't work

### ISSUE THREAD

**Issue by slavasitnikov** [pinojs/pino#418]
http://getpino.io/#/docs/API?id=level

Changing minimum logging level doesn't work as described in the documentation.

```
const pino = require("pino")({
  level: "info"
});

pino.info("display. OK");
pino.trace("doens't display. OK");

pino.level = "trace";
pino.trace("doens't display. ERROR");
```

pino version:  4.16.1

**Comment by mcollina** [comment]
ouch! Would you like to send a PR?

**Comment by davidmarkclements** [comment]
this is also a docs problem

the browser API and the server API are not the same, we might need create a browser API section

**Comment by davidmarkclements** [comment]
the reason dynamic level wasn't included in browser pino is as follows

* browser pino needs to be as small a payload as possible
* there isn't a strong use case for setting the level dynamically (instead of via config) – EXCEPT for debugging
* first pass at browser pino therefore didn't include dynamic level setting

However, if we consider this a must-have, then that's cool let's put it in

**Comment by slavasitnikov** [comment]
@mcollina ok, i'll do it
