### ISSUE TITLE
Add options to turn off `level` and `v` properties

### ISSUE THREAD

**Issue by paranoid-android** [pinojs/pino#430]
Hello,

Pino lets a developer remove all of the pre-defined log properties *except* for `level` and `v`. For example, a developer can configure a logger like this:

```
let logger = pino({
  base: null,
  timestamp: false
}, fs.createWriteStream('./log.json'));

logger.info({ message:'hello world'});
```

This will generate a log that looks like this:

```
{"level":30,"message":"hello world","v":1}
```

It would be great to be able to remove *all* pre-defined properties so only the message or text that a developer wants to log would appear.

**Comment by mcollina** [comment]
@paranoid-android I'm not sure that adds value. levels play a huge role in pino, and I'm not sure I see the use case. Can you please elaborate?

**Comment by paranoid-android** [comment]
The reason to remove the 'level' property is just to give a developer full control over the log that's output.

**Comment by marcbachmann** [comment]
One use case where `level` might not fit is if you want to track events in an application, but there I would rather use a custom loglevel instead of removing the property. It might also be annoying to see whether something is a line from pino or from somewhere else if we remove all the properties.

To the schema version:
I'd support the removal of `v` as I don't see any benefit in it of it.
Isn't the declaration of the npm module version already good enough and a bit redundant to `v`?

If the root-level properties would be fixed, then it would make sense, but as everything completely depends on the usage of pino, any change could break the log collection on a server. 

E.g. A simple value change like
```json
{"customValue": {"test": "foo"}}
```
to
```json
{"customValue": "foo"}
```
can break the log pipeline if elasticsearch is in use. Since changing custom values can have a much bigger impact, I see no reason to use `v`. The custom version attribute or schema-id should be declared on a higher level construct (like with annotations on a service in kubernetes or using the `base` option).

**Comment by davidmarkclements** [comment]
v pertains to the version of the log format. This will become important if certain log conventions change. Neither the npm version nor service versioning will cover that

**Comment by jsumners** [comment]
And it's basically the only property we can use to determine a Pino log line in downstream transports.

**Comment by davidmarkclements** [comment]
@paranoid-android without the `level` the semantics of the logger (e.g. `logger.info`) are meaningless. If you want high speed writes, but don't want the trappings of Pino you can use the underlying lib that pino uses: <https://www.npmjs.com/package/sonic-boom>

As for removing `v` we could recommend against it, however if anyone wants to create a PR that configures Pino to log without `v` (and possibly to rename it as well) we would consider it. 

closing for now as we've come to a conclusion on this

**Comment by wjabbour** [comment]
What if you wanted to provide your own names for the levels, instead of numbers how about strings?
