### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by SidKwok** [pinojs/pino#431]
I built a web application, and need to store some information in local file, one request a file.

I built it with pino, but when 20 requests are coming, I will receive a warning like `MaxListenersExceededWarning`.

Here is a very simple example, I use `for` to modify the requests:

```js
const pino = require('pino');
const fs = require('fs');
for (let i = 0; i < 20; i++) {
    (name => {
        const pretty = pino.pretty();
        // each request has an output file,
        // and the information will be collected this file
        pretty.pipe(fs.createWriteStream(`${name}`.log));

        // I use this logger to collect info
        const logger = pino({name}, pretty);
        logger.info('some unique information about each request');
    })(i)
}
```

How can I avoid this warning?

**Comment by davidmarkclements** [comment]
this is an anti pattern - you should avoid adding lots of destinations to a stream because it leads to a memory leak (which is why you're getting the warning). This also won't work because the files will all continue to write for all logs. If you want one log per file you need to create one logger per file. However I think your goal is associate loggers with requests - to do this use one of pino's web framework libraries - hapi-pino, express-pino-logger, pino-http etc
