### ISSUE TITLE
Global serializer not invoked for strings when `base: null`

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#479]
```js
'use strict'

const pino = require('pino')
const log = pino({
  base: null,
  serializers: {
    [Symbol.for('pino.*')]: (input) => {
      console.log('global serializer invoked')
      return input
    }
  }
})

log.info('does not invoke global serializer')
log.info({will: 'invoke global serializer'})
```

But this will work as expected:

```js
'use strict'

const pino = require('pino')
const log = pino({
//  base: null,
  serializers: {
    [Symbol.for('pino.*')]: (input) => {
      console.log('global serializer invoked')
      return input
    }
  }
})

log.info('will invoke global serializer')
log.info({will: 'invoke global serializer'})
```

**Comment by mcollina** [comment]
Ouch, good spot!

**Comment by jsumners** [comment]
Shouldn't the global serializer receive the complete log object, including things like the `level` property? Otherwise, it seems like an *almost* global serializer; not a global one.

**Comment by davidmarkclements** [comment]
Yeah id say it's a bug - if it's also a bug in v4 we should probably backport the fix

**Comment by jsumners** [comment]
Another question: should other serializers be applied prior to this one? I'm thinking so. I think the global should be the immediately last step prior to building the JSON string.

**Comment by mcollina** [comment]
> Shouldn't the global serializer receive the complete log object, including things like the level property? Otherwise, it seems like an almost global serializer; not a global one.

@jsumners the global serializer is applied to the object that is passed, not to the object that is going to be generated. `msg`, `time`, `level` etc will not be there, and it was never the design.

> Another question: should other serializers be applied prior to this one? I'm thinking so. I think the global should be the immediately last step prior to building the JSON string.

I think the current approach is fine, as long as we document it. Moving it _after_ would be impossible for us because of how we are composing the final object, and we'll have to it a very slow path.

> What we should probably have done was a pre and post global serialiser, we could solve this by adding pre/post symbols and deprecating global (then remove in 6)

@davidmarkclements I would rather not. That code path is already _too_ complicated.

**Comment by davidmarkclements** [comment]
@mcollina I agree.

**Comment by raine** [comment]
I have a logger initialized with a global serializer and *without* `base: null` yet the serializer function is not getting called unless a log method is called with an object as the first argument. Related to this issue or am I misusing the library?

```typescript
const options: pino.LoggerOptions = {
  serializers: {
    [Symbol.for('pino.*')]: (input) => {
      console.log('xxx')
      return {
        ...input,
        reqId: httpContext.get('reqId')
      }
    }
  }
}

const log = pino(options, destination)
```


```js
log.info({}, 'foo')
log.info('foo')
```

```
xxx
{"level":30,"time":1539421623952,"msg":"foo","pid":5706,"reqId":"5a0c9d30-cec7-11e8-a2b5-8bc17d6718c8","v":1}
{"level":30,"time":1539421623952,"msg":"foo","pid":5706,"v":1}
```

**Comment by yellowbrickc** [comment]
As I promised, I tried today to find the correct place to fix this bug.
At the moment I see 2 possibilities:

1. Consider the param "msg" as a prop of the param "obj":
https://github.com/pinojs/pino/blob/master/lib/tools.js#L82-L84
Instead adding the param "msg" to the output json string the whole param could be merged with the other param "obj". Then could the condition if(hasObject) be removed because always true. 
Problem: I could imagine that the separation of the 2 params was in purpose

2. Extract the serialization logic and apply it to the string message:
https://github.com/pinojs/pino/blob/master/lib/tools.js#L97-L129
Parts of those lines must be extracted.
This variant would have less side effects but it is hard to extract the correct transformation logic because of the currently existing side effects (reassignment to the same vars). But I think this is the less offensive way.

What do you think?

**Comment by mcollina** [comment]
> Consider the param "msg" as a prop of the param "obj":
https://github.com/pinojs/pino/blob/master/lib/tools.js#L82-L84
Instead adding the param "msg" to the output json string the whole param could be merged with the other param "obj". Then could the condition if(hasObject) be removed because always true.
Problem: I could imagine that the separation of the 2 params was in purpose

It was on purpose. The reason is to avoid adding another property to an object, as it will prohibit some optimizations in V8. It might be worthwhile to try anyway.

> Extract the serialization logic and apply it to the string message:
https://github.com/pinojs/pino/blob/master/lib/tools.js#L97-L129
Parts of those lines must be extracted.
This variant would have less side effects but it is hard to extract the correct transformation logic because of the currently existing side effects (reassignment to the same vars). But I think this is the less offensive way.

That part is highly sensitive and part of our hot path. Again, I'm +1 if the benchmarks say "it's ok".

I'm wondering if we could just create an empty object as a base instead.

**Comment by yellowbrickc** [comment]
I have chosen variant 1, please have a look at the PR

**Comment by davidmarkclements** [comment]
closing because I think this was addressed
