### ISSUE TITLE
Question: send method for node code?

### ISSUE THREAD

**Issue by justinhelmer** [pinojs/pino#583]
I love the concept of `send` to allow the browser to post a message to some external service for log management. However, it would also be nice to do something similar on the node layer.

I'm guessing you are going to tell me that it is a bad idea because we don't want to block the process while the async post is happening, but what would you recommend for a universal codebase like React/Vue? I don't know about any streams libraries that are universal, so I'm not sure how I could create a custom transport to handle this. Can you provide an example?

Thanks a lot.

**Comment by davidmarkclements** [comment]
the `send` method is browser substitute for Pino transports, please see the docs, http://getpino.io/#/docs/transports

**Comment by justinhelmer** [comment]
I understand that point, but we are writing universal code. I'm wondering if there is a common solution we can write without having to create a custom alias that references two different pino instances depending on client/server

**Comment by davidmarkclements** [comment]
yeah I get you, the problem is when it comes to balancing performance with ideal API's for I/O the constraints of browser vs server environment forces our hand somewhat. For instance, we don't advocate for sending logs from within the process on the server side, since this will put extra pressure on the event loop and gc. Instead we recommend piping output to somewhere else for post-processing. The philosophy of this project has always been performance first, often times server side performance is sacrificed for universal code ideal (e.g., react server side rendering). However, now with worker threads in Node we might be able to introduce a universal API, but this will require an overhaul of Pino transports - it's non-trivial.

**Comment by justinhelmer** [comment]
ok thanks for the thoughtful response. makes sense.
