### ISSUE TITLE
Pino + loggly

### ISSUE THREAD

**Issue by akaNightmare** [pinojs/pino#628]
I am wondering how to use loggly transport for pino logger?

**Comment by mcollina** [comment]
I haven't use loggly in a long time, and never with pino.

I would use https://www.loggly.com/docs/http-bulk-endpoint/ or https://www.loggly.com/docs/http-bulk-endpoint/

**Comment by psypersky** [comment]
Im also checking at this logger @akaNightmare, from what I understand this logger doesn't believe in Transports inside the app/logger, you need to pipe it or send it to your transport in a different manner

Example 1 (AWS ECS):
Pino in an ECS container logs to stdout, logs then go to cloudwatch and then you can run a lambda to process the logs and send them to loggly https://www.loggly.com/docs/cloudwatch-logs/

Example 2:
Pino in a node.js service logs to stdout, you pipe the node.js app to your custom transport `node myApp.js | myLogglyTransport.js`

Example 3:
Pino logs to a file and then you run some transport each X time that takes that file and send it to somewhere

I was hesitant to do this because the re-parsing involved in not using in-app transports, but after thinking it a bit its totally worth it, your logger won't die with your app. Cool Project @mcollina 👌🏽

**Comment by mcollina** [comment]
You can avoid re-parsing. We might want to expose that logic better, but here it is: https://github.com/pinojs/pino/blob/master/lib/tools.js#L180-L265.

Note that with most APIs you can actually generate JSON by concatenating strings, and send data there that way. It'll be significantly faster.

---

The problem on why we don't believe logger in the main loop is that they are going to blow up a) CPU usage b) memory consumption on the first glimpse of a problem. As a result, they are not really what you want to run in production.

**Comment by akaNightmare** [comment]
Thanks for replying, anyway Pino need some mechanism from the box to use some transports such as loggly, elasticsearch, mognodb and etc, because sometimes stdour/err is not enough for business purposes. I found that there is exist some PR (RFC) to supports transports https://github.com/pinojs/pino/pull/614 , however it would be great to have some recommendations from the core team how to handle similar situations.

Thank you.

**Comment by jsumners** [comment]
Pino provides a logging framework you can use to implement what you need. We are not writing free (as in beer) code for every business use case that can possibly exist. The way you setup your environment will dictate how you store your logs. Pino allows you the flexibility to determine that solution.
