### ISSUE TITLE
Get data from logger

### ISSUE THREAD

**Issue by SanthoshRonin** [pinojs/pino#641]
Hi,
  Is there any possibilities to get the logger data instead of writing it to a file. I want to store the logger information to my database. So that i need the data. Somebody please tell me how to get the data as a object .

**Comment by mcollina** [comment]
I would recommend against that, for two reasons:

1. writing log _directly_ to a database adds another potential source of problems to a production system. What happens if that goes down or has some difficulties?

2. you are increasing the amount of data and processing your application needs to do for every request.

I recommend to log to stdout and then rely on infrastructure to move the data.

You can do that by implementing a custom stream, like so: https://github.com/pinojs/pino/blob/d51220dd8a08a8f7ba44504ea262f75cb957f87f/lib/tools.js#L165-L240
