### ISSUE TITLE
Is pino-stack-info an official Pino package?

### ISSUE THREAD

**Issue by AaronFriel** [pinojs/pino#660]
While looking for a lightweight way to add stack traces to certain messages, I stumbled across this low utilization package:

https://www.npmjs.com/package/pino-stack-info/v/5.11.1

It appears this is a fork of pino with some changes, and it looks suspicious to my eyes because the homepage, repository, etc. point to this project, but nothing here publishes to `pino-stack-trace`.

**Comment by jsumners** [comment]
No, that is definitely not "official". I certainly have never heard of it, or the author, before this issue.

The author seems to have made one commit since their fork https://github.com/tqcenglish/pino-stack-info/commit/9d603a44bdb3c72a246e7a816a3f7345727f1e87 . It doesn't look like a malicious change. It looks like this is just someone who doesn't work well with an open source community.

**Comment by davidmarkclements** [comment]
@AaronFriel for stack traces there's https://github.com/pinojs/pino-caller 

this was created by a collaborator and reviewed by the core team
stack traces are inherently expensive however, so "lightweight" is a challenge here.

If you're looking to enable traces for specific levels, you might need to PR pino-caller

extra context: https://github.com/pinojs/pino/issues/191

**Comment by AaronFriel** [comment]
Thanks, I was curious about the status of the package and wanted to alert anyone who might be concerned that it appears to be an official Pino package, and there's nothing preventing the packages source from differing from the GitHub repo.

@davidmarkclements for logging exceptions, my requirements were somewhat specific to match Stackdriver's logging and error alerting, so I ended up writing my own `logWithStack` function. Thank you though!
