### ISSUE TITLE
Avoid duplicate key

### ISSUE THREAD

**Issue by allevo** [pinojs/pino#682]
Hi!
My application is like this:
```js
const log = pino()
const child = log.child({ key: 'value' })
child.info({ key: 'foo' })
```
The output is like this
```json
{ ... "key":"value","key":"foo", ... }
```

In some situation, having logs with duplicate keys is a problem.
For example, I have [Fluent Bit](https://fluentbit.io/) daemon that reads logs, parses them a pushes them to ElasticSearch. Currently the fluent bit daemon is not able to drop the duplicate keys and [ES responses 400](https://discuss.elastic.co/t/json-technically-allows-for-duplicate-keys-do-elasticsearch-documents/118526/4).

I would like to send a PR in order to add a feature flag that allow you to avoid key duplication.
Are you interested in this kind of feature?

The main idea is to track in a structure which keys are already serialized during `child` function call to avoid to serialize a key/value pair if the key is in the structure.

**Comment by davidmarkclements** [comment]
this is expected behaviour - trade off already made between performance and this issue, explanation here http://getpino.io/#/docs/help?id=dupe-keys

the two ways to handle this are: don't have duplicate keys, or use a transport to strip duplicates outside of the process

closing for now as this is an already well discussed characteristic, please read the docs and check old issues/pr's for your problem before opening

**Comment by arbourd** [comment]
Thanks for the link and context here though David. Google suggest this issue first 😅
