### ISSUE TITLE
Logger not show message in debug console (chrome, webstrom)

### ISSUE THREAD

**Issue by grkov90** [pinojs/pino#691]
Hello, in debug console I see only ```'console.log'```

```
//app.js
const pino = require('pino')

const log = pino();

console.log('console.log')
log.info('pino info')

setTimeout(() => {}, 10000)
```
Run it ```node --inspect-brk app.js``` and connect from webstorm or chrome remote debug.

**Comment by JoelJaimeB** [comment]
Hi @grkov90 apparently the **log, trace, etc** methods only work from the machine's local terminal:
![Captura de Pantalla 2019-08-08 a la(s) 3 54 49 p  m](https://user-images.githubusercontent.com/1984746/62733561-e49a7f80-b9f4-11e9-950e-ca9857caf87d.png)
Since since the item inspector (specifically from Google Chrome) does not seem to work, I will have to see the behavior in other browsers.

**Comment by grkov90** [comment]
![image](https://user-images.githubusercontent.com/1639876/62760613-195a1580-ba8d-11e9-8992-5f99fb044939.png)

**Comment by mcollina** [comment]
You can use https://github.com/pinojs/pino-inspector.

**Comment by grkov90** [comment]
@mcollina it works, thx)
