### ISSUE TITLE
Level-based redaction

### ISSUE THREAD

**Issue by dougmoscrop** [pinojs/pino#703]
I often find myself writing semi-duplicated code because I want to log some fact, but there may be something else (easy example is a request payload) that I might want to know some times, but I certainly don't want to write all the time.  Yes, I can just write two log statements, but it would be neat if I could configure a redactor to treat something like foo.request.body as a trace level, but foo.request.headers as debug level, and so on.

I think maybe the actual gruntwork would be in the redaction library itself, and the goal would be to make it something you don't pay a cost for unless you use it.

This is just an idea at this point, looking for alternative ideas or maybe existing options.

**Comment by mcollina** [comment]
I have a feeling this might get very costly (in term of performance) very quickly. 

I don’t really understand how this would work api-wise, would you like to make an example?

**Comment by davidmarkclements** [comment]
Actually... if you described the parts of the object you want to log with
json schema this could be made very fast - Matteo I’m thinking we can use
the fastify parser lib. Rather than redacting properties, you’d instead
describe the properties you want to log at different log levels. From that
we would precompile functions (we can lazy compile them, so for most use
cases we only have to precompile one function).

This could actually be a way to log request bodies at the highest possibly
performance, the trade off is you have to describe the entire nested
structure (including what’s in the body) for the optimisation to be
effective.

Alternatively we could combine the strategy with turbo json parse....

**Comment by dougmoscrop** [comment]
I'm certainly just an end user here but I figured that if redaction can be done fast, readacting based on target log level could be done fast too. You might even be able to use some kind of virtual path hack to treat the current/target log level as just paths within an object?

**Comment by mcollina** [comment]
Yes and no. Adding level-based redaction complicates inlining by V8 of some of our logic, which has no level-specific behavior so far. This is feasible, it’s just that it requires some work to make it happen. Would you like to work on a PR?

**Comment by dougmoscrop** [comment]
I'd love to, not sure I have the time right now, but I will keep it on my list!

**Comment by Fdawgs** [comment]
Closed by #1059 ?
