### ISSUE TITLE
Call pino.destination as pino.sync and pino.extreme as pino.async

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino#785]
Operationally they provide two very different approaches and I think we would be best to not call `extreme()` as a drastic measure but rather `async()` because that reflect what it is without making judgements.

**Comment by mcollina** [comment]
cc @davidmarkclements @jsumners

**Comment by jsumners** [comment]
Sounds good to me.

**Comment by davidmarkclements** [comment]
`async` is an overloaded word, we can simplify the API:

1. deprecate `extreme`
2. add an option to `destination` - `blocking` (Boolean) default: true (may also be called `sync` instead of blocking
3. If we can elegantly solve the exit flushing problem in a current/future version of node we can make `blocking` (or `sync`) false by default for those Node versions

**Comment by mcollina** [comment]
https://github.com/mcollina/sonic-boom/pull/35 should implement the important bit sonic-boom wise.

**Comment by mcollina** [comment]
Done in #791
