### ISSUE TITLE
A broken link in readme.md

### ISSUE THREAD

**Issue by eduard-malakhov** [pinojs/pino#805]
The link 'Extreme Mode ⇗' in the main readme leads to https://github.com/pinojs/pino/blob/master/docs/extreme.md which does not exist.

**Comment by eduard-malakhov** [comment]
The same in the docs: http://getpino.io/#/docs/extreme

**Comment by chaffeqa** [comment]
As a note, the changelog does **not** do a good job highlighting the deprecation of `extreme` mode... just to add on to this confusion

**Comment by mcollina** [comment]
Would you like to issue a PR to solve all of this? Note that `extreme` mode is renamed in `sync: false` on `pino.destination()`. It's simpler and more coherent. There is nothing "extreme" in using "extreme mode" anymore.

**Comment by chaffeqa** [comment]
ha yeah i noticed that after reading the deprication in the server logs 😆

So the biggest gripe to me was that after reading the deprication, i went to http://getpino.io/ and it still had the section on `extreme()`, however now that looks like its 404'ing.

I'd love to do a PR, but frankly im not so sure I understanding the doc release cycle, since after going to the website, i looked at the Changelog, didnt see anything that stood out, and then finally looked at the source code which seemed to change the `asynchronouse.md` file... hence arriving at the final conclusion

**Comment by mcollina** [comment]
The website only reflect master. There is no published doc (yet) for previous release lines.

**Comment by AleksandrSl** [comment]
Will be fixed by #838 I think
