### ISSUE TITLE
pino issues `process.exit` when it isn't the controlling process

### ISSUE THREAD

**Issue by jsumners** [pinojs/pino#92]
When pino is in "extreme" mode it has to register handlers for `process.on('exit')` (https://github.com/mcollina/pino/blob/master/pino.js#L390). These handlers are necessary so that pino can flush the extreme mode cache prior to the process exiting, or else there is the potential for data loss. After flushing the cache, pino then checks to see if its events are in the event queue (https://github.com/mcollina/pino/blob/master/pino.js#L98). If so, pino issues a `process.exit()`.

It is my opinion that a logger should not be invoking `process.exit`. That should be left up to the application that included pino. However, once event handlers are registered on `process` the process doesn't respond to signals like `SIGTERM` normally; at this point it is up to the application to deal with those signals.

I think there are a couple possible solutions:
1. instead of issuing `process.exit` pino can issue its own "exit" event so that the actual application can do what it needs to do for shutdown
2. pino can accept a callback during initialization that will be invoked after the cache flushing

In either case, this moves the responsibility of terminating the process to the actual application. And it removes the surprise `process.exit` within pino.

Thoughts, @mcollina @davidmarkclements ?

**Comment by davidmarkclements** [comment]
We did discuss this very thing (point 2) early on with a view to reviewing current impl. later

I think 2 is best, extreme mode is for advanced users, we just need to explain in docs

@mcollina what do you think?

**Comment by mcollina** [comment]
We need to change the current behavior, as accessing _events will become unsupported in the near future (there is a core issue on this).

IMHO the current behavior is ok. If extreme mode is enabled, the fact that pino listens to some global event should be transparent: if there is no one listening, we should 

The other option is letting the user decide, and not opt them in. We already expose flush(), it is just a refactoring to make it sync, and document a way on how to call flush() correctly. Or maybe offer an handy method that does what we do now.

I disagree on offering the user a callback on creation.

**Comment by jsumners** [comment]
I have been working on the callback method and it is proving very difficult to test. I agree with @mcollina that it is not an optimal solution.

I like the idea of requiring `flush()` to be called for a proper shutdown in extreme mode.

**Comment by mcollina** [comment]
I think we may want an extreme mode and a flushBeforeExit thing, that enables the current behavior.

**Comment by davidmarkclements** [comment]
Like `pino({flushBeforeExit: true})` ?- but who's not going to want that by default? 

It's tricky because any of the currently discussed options require explanation,

flushing if no event handler and then not flushing if there is maybe too indirect from a usability perspective, I think we should do or require one action in every case, so making them set up their own handler and then calling flush is most explicit - but then we can do that for them via config option (flushBeforeExit) - and then like I say who is *not* going to want that by default in extreme mode, so if we enable it by default we're pretty much back to square one except you can turn exit handling off

**Comment by mcollina** [comment]
Being able to turning them off would be a nice win anyway. Also documenting those handlers, etc, and make sure someone could do it themselves.

I'm ok eiher to provide a snippet for people to use, an option to turn it off, and a flush method.
So, how do we want to solve it?

We will need to refactor that code anyway to remove _events access.

**Comment by jsumners** [comment]
I would rather one of you guys tackle this one. I'm not confident I can write proper tests to verify the functionality is working as intended.

**Comment by davidmarkclements** [comment]
I think we still have yet decide the right approach here - @jsumners you wouldn't happen to be coming to nodeconf.eu would you?

**Comment by jsumners** [comment]
@davidmarkclements that would be awesome, but I've never even been out of the States (i.e. don't even have a passport). If you're ever in/passing through Atlanta, GA though, hit me up and we'll get a drink.

As for the approach, I'm not sure on that either. It's a tricky problem.

**Comment by davidmarkclements** [comment]
You're in Atlanta? I was there a few months back - will do, will do
There's a node interactive happpening in austin in nov btw... (@mcollina and I will be there)

For approach I'll see if we can hammer something down and come back

**Comment by jsumners** [comment]
I'll investigate going to Austin. However, the academic pricing seems fair (if they allow staff and not just students and faculty), but I don't think I'd be able to afford the whole trip.

**Comment by davidmarkclements** [comment]
Bumping as reminder for this to be discussion point in austin @jsumners @mcollina

**Comment by mcollina** [comment]
We can divide this problem into three cases:

1. events that have still an event loop running, and we can wait for the `fd` to be available: 
  a. `beforeExit`
  b. `SIGHUP`
  c. `SIGQUIT`

2. events that will result in the process to exit no matter what we do (no event loop running)
  a. `exit`

3. `SIGTERM`, `SIGINT` and `uncaughtException`  are special, because they will change the behaviour of the node process, see:

> SIGTERM and SIGINT have default handlers on non-Windows platforms that resets the terminal mode before exiting with code 128 + signal number. If one of these signals has a listener installed, its default behavior will be removed (Node.js will no longer exit).

At the moment we are handling all of them in the same way, but we should not. For case 1), we should schedule a little timer and poll for the `fd` to be available, and then quit. In case 2), we should not crash, we do not clean up properly, there is no need `process.exit()`.

For case 3) we want to be ghosts, and not interfere with what the user wants to do.

For `uncaughtException` we should probably log for `fatal`.

**Comment by jsumners** [comment]
Notes because I have almost forgotten them:

Case 1 is necessary for extreme mode to work correctly.

Case 2 is outlined in issue #131.

Case 3 is the original concern that prompted this issue (#92).

**Comment by mcollina** [comment]
I did (damn). Is this waiting for me to do something?

**Comment by jsumners** [comment]
I think it's waiting on any of us to do something, @mcollina . I still haven't been able to think of a solution, so I haven't done anything.

**Comment by jsumners** [comment]
Fixed by #187
